src/Lantern/AuthBundle/Entity/Group.php
<?php

namespace Lantern\AuthBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Role
 */
class Group implements \Serializable
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $shortName;

    /**
     * @var string
     */
    private $longName;

    /**
     * @var string
     */
    private $description;

    /**
     * @var boolean
     */
    private $isActive;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $children;

    /**
     * @var \Lantern\AuthBundle\Entity\Group
     */
    private $parent;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $users;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $roles;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
        $this->users    = new \Doctrine\Common\Collections\ArrayCollection();
        $this->roles    = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * @see \Serializable::serialize()
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
        ));
    }

    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized)
    {
        list (
            $this->id,
        ) = unserialize($serialized);
    }


    public function getGroup()
    {
        return $this->getShortName();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set shortName
     *
     * @param string $shortName
     * @return Group
     */
    public function setShortName($shortName)
    {
        $this->shortName = $shortName;
    
        return $this;
    }

    /**
     * Get shortName
     *
     * @return string 
     */
    public function getShortName()
    {
        return $this->shortName;
    }

    /**
     * Set longName
     *
     * @param string $longName
     * @return Group
     */
    public function setLongName($longName)
    {
        $this->longName = $longName;
    
        return $this;
    }

    /**
     * Get longName
     *
     * @return string 
     */
    public function getLongName()
    {
        return $this->longName;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Group
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return Group
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;
    
        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * Add children
     *
     * @param \Lantern\AuthBundle\Entity\Group $children
     * @return Group
     */
    public function addChildren(\Lantern\AuthBundle\Entity\Group $children)
    {
        $this->children[] = $children;
    
        return $this;
    }

    /**
     * Remove children
     *
     * @param \Lantern\AuthBundle\Entity\Group $children
     */
    public function removeChildren(\Lantern\AuthBundle\Entity\Group $children)
    {
        $this->children->removeElement($children);
    }

    /**
     * Get children
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * Set parent
     *
     * @param \Lantern\AuthBundle\Entity\Group $parent
     * @return Group
     */
    public function setParent(\Lantern\AuthBundle\Entity\Group $parent = null)
    {
        $this->parent = $parent;
    
        return $this;
    }

    /**
     * Get parent
     *
     * @return \Lantern\AuthBundle\Entity\Group 
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Add users
     *
     * @param \Lantern\AuthBundle\Entity\User $users
     * @return Role
     */
    public function addUser(\Lantern\AuthBundle\Entity\User $users)
    {
        $this->users[] = $users;
    
        return $this;
    }

    /**
     * Remove users
     *
     * @param \Lantern\AuthBundle\Entity\User $users
     */
    public function removeUser(\Lantern\AuthBundle\Entity\User $users)
    {
        $this->users->removeElement($users);
    }

    /**
     * Get users
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        return $this->roles->toArray();
    }

    /**
     * Add roles
     *
     * @param \Lantern\AuthBundle\Entity\Role $roles
     * @return User
     */
    public function addRole(\Lantern\AuthBundle\Entity\Role $roles)
    {
        $this->roles[] = $roles;
    
        return $this;
    }

    /**
     * Remove roles
     *
     * @param \Lantern\AuthBundle\Entity\Role $roles
     */
    public function removeRole(\Lantern\AuthBundle\Entity\Role $roles)
    {
        $this->roles->removeElement($roles);
    }

    public function __toString()
    {
        return (string) $this->getShortName();
    }
}

src/Lantern/AuthBundle/Form/GroupType.php
<?php

namespace Lantern\AuthBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class GroupType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('shortName')
            ->add('longName')
            ->add('description')
            ->add('isActive')
            ->add('parent')
            ->add('children')
            ->add('roles')
            ->add('users')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Lantern\AuthBundle\Entity\Group'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'lantern_authbundle_group';
    }
}

src/Lantern/AuthBundle/Controller/GroupController.php
<?php

namespace Lantern\AuthBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Lantern\AuthBundle\Entity\Group;
use Lantern\AuthBundle\Form\GroupType;

/**
 * Group controller.
 *
 */
class GroupController extends Controller
{

    /**
     * Lists all Group entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('LanternAuthBundle:Group')->findAll();

        return $this->render('LanternAuthBundle:Group:index.html.twig', array(
            'entities' => $entities,
        ));
    }
    /**
     * Creates a new Group entity.
     *
     */
    public function createAction(Request $request)
    {
        $entity = new Group();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('LanternAuthBundle_group_view', array('id' => $entity->getId())));
        }

        return $this->render('LanternAuthBundle:Group:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
    * Creates a form to create a Group entity.
    *
    * @param Group $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createCreateForm(Group $entity)
    {
        $form = $this->createForm(new GroupType(), $entity, array(
            'action' => $this->generateUrl('LanternAuthBundle_group_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Group entity.
     *
     */
    public function newAction()
    {
        $entity = new Group();
        $form   = $this->createCreateForm($entity);

        return $this->render('LanternAuthBundle:Group:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Group entity.
     *
     */
    public function viewAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('LanternAuthBundle:Group')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Group entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('LanternAuthBundle:Group:view.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),        ));
    }

    /**
     * Displays a form to edit an existing Group entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('LanternAuthBundle:Group')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Group entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('LanternAuthBundle:Group:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
    * Creates a form to edit a Group entity.
    *
    * @param Group $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Group $entity)
    {
        $form = $this->createForm(new GroupType(), $entity, array(
            'action' => $this->generateUrl('LanternAuthBundle_group_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing Group entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('LanternAuthBundle:Group')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Group entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('LanternAuthBundle_group_edit', array('id' => $id)));
        }

        return $this->render('LanternAuthBundle:Group:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }
    /**
     * Deletes a Group entity.
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('LanternAuthBundle:Group')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Group entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('LanternAuthBundle_group_index'));
    }

    /**
     * Creates a form to delete a Group entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('LanternAuthBundle_group_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm()
        ;
    }
}

src/Lantern/AuthBundle/Resources/views/Group/edit.html.twig
{% extends '::base.html.twig' %}

{% set pageIcon = 'group' %}
{% set pageTitle = 'admin.panel'|trans %}
{% set pageSubtitle = 'edit.group'|trans %}
{% set active = 'LanternAuthBundle_group_index' %}

{% block navBody %}
    {% include 'LanternAdminBundle::nav.html.twig' %}
{% endblock navBody %}

{% block contentBody -%}
    <h1>Group edit</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('LanternAuthBundle_group_index') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock contentBody %}

src/Lantern/AuthBundle/Resources/views/Group/index.html.twig
{% extends '::base.html.twig' %}

{% set pageIcon = 'group' %}
{% set pageTitle = 'admin.panel'|trans %}
{% set pageSubtitle = 'groups'|trans %}
{% set active = 'LanternAuthBundle_group_index' %}

{% block navBody %}
    {% include 'LanternAdminBundle::nav.html.twig' %}
{% endblock navBody %}

{% block contentBody -%}
    <table class="table table-bordered table-striped table-condensed table-hover">
        <thead>
            <tr>
                <th><input type="checkbox" class="select-all" /></th>
                <th>{{ 'actions'|trans }}</th>
                <th>{{ 'short.name'|trans }}</th>
                <th>{{ 'long.name'|trans }}</th>
                <th>{{ 'description'|trans }}</th>
                <th>{{ 'status'|trans }}</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td><input type="checkbox" /></td>
                <td>
                    <div class="btn-group" role="group" aria-label="{{ 'group.actions'|trans }}">
                        <a href="{{ path('LanternAuthBundle_group_view', { 'id': entity.id }) }}" class="btn btn-xs btn-default" title="{{ 'view'|trans }}">
                            <span class="fa fa-search-plus"></span>
                        </a>
                        <a href="{{ path('LanternAuthBundle_group_edit', { 'id': entity.id }) }}" class="btn btn-xs btn-default" title="{{ 'edit'|trans }}">
                            <span class="fa fa-pencil"></span>
                        </a>
                    </div>
                </td>
                <td>{{ entity.shortName }}</td>
                <td>{{ entity.longName }}</td>
                <td>{{ entity.description }}</td>
                <td>
                    {% if entity.isActive %}
                        <span class="label label-success">{{ 'active'|trans }}</span>
                    {% else %}
                        <span class="label label-danger">{{ 'inactive'|trans }}</span>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        <ul>
        <li>
            <a href="{{ path('LanternAuthBundle_group_new') }}">
                Create a new entry
            </a>
        </li>
    </ul>
{% endblock contentBody %}

src/Lantern/AuthBundle/Resources/views/Group/new.html.twig
{% extends '::base.html.twig' %}

{% set pageIcon = 'group' %}
{% set pageTitle = 'admin.panel'|trans %}
{% set pageSubtitle = 'new.group'|trans %}
{% set active = 'LanternAuthBundle_group_index' %}

{% block navBody %}
    {% include 'LanternAdminBundle::nav.html.twig' %}
{% endblock navBody %}

{% block contentBody -%}
    <h1>Group creation</h1>

    {{ form(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('LanternAuthBundle_group_index') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock contentBody %}

src/Lantern/AuthBundle/Resources/views/Group/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Group</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entity.id }}</td>
            </tr>
            <tr>
                <th>Shortname</th>
                <td>{{ entity.shortName }}</td>
            </tr>
            <tr>
                <th>Longname</th>
                <td>{{ entity.longName }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ entity.description }}</td>
            </tr>
            <tr>
                <th>Isactive</th>
                <td>{{ entity.isActive }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('group') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('group_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/Lantern/AuthBundle/Resources/views/Group/view.html.twig
{% extends '::base.html.twig' %}

{% set pageIcon = 'group' %}
{% set pageTitle = 'admin.panel'|trans %}
{% set pageSubtitle = 'view.group'|trans %}
{% set active = 'LanternAuthBundle_group_index' %}

{% block navBody %}
    {% include 'LanternAdminBundle::nav.html.twig' %}
{% endblock navBody %}

{% block contentBody -%}
    <h1>Group</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entity.id }}</td>
            </tr>
            <tr>
                <th>Shortname</th>
                <td>{{ entity.shortName }}</td>
            </tr>
            <tr>
                <th>Longname</th>
                <td>{{ entity.longName }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ entity.description }}</td>
            </tr>
            <tr>
                <th>Isactive</th>
                <td>{{ entity.isActive }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('LanternAuthBundle_group_index') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('LanternAuthBundle_group_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock contentBody %}